name: Test

on: [push]

env:
  RAILS_ENV: test

jobs:
  tests:
    name: Run rubocop, rspec and javascript tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - name: Set up yarn cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node.js dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Set up test database
        run: bin/rails db:prepare
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test

      - name: Run tests
        run: bundle exec rake
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
